version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '8888:5432'
    env_file:
      - .env.dev
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
